default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dialog
  password: <%= ENV['DIALOG_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: dialog_development

test:
  <<: *default
  database: dialog_test

production:
  <<: *default
  url: <%= ENV['DIALOG_DATABASE_URL'] %>
